[build]
  base    = "client"
  command = "npm run build -- --configuration production"
  publish = "dist/patocup-front/browser"

# Redirige todas las rutas al index.html para que Angular Router funcione
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
